linters:
  enable:
  - errname
  - errorlint
  - errcheck
  - errorlint
  - unused
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - gosec
  - misspell
  - revive
  - thelper
  - unconvert
  - unconvert
  - whitespace
  - staticcheck
  disable:
  - structcheck

linters-settings:
  depguard:
    list-type: 'denylist'
    packages-with-error-message:
      - 'github.com/pkg/errors': 'the github.com/pkg/errors is deprecated, use stdlib instead'
